### ISSUE TITLE
Paul request: add new facet

### ISSUE THREAD

**Issue by nessita** [revsys/revsys-nuremberg#196]
Please add facet of "Search Type" to facet listing on search-results page (first facet to be listed); the instance numbers are just examples, of course:
![search_type](https://user-images.githubusercontent.com/124304/221178910-ec758395-db2a-4c85-80be-fc9dd4079531.jpg)

**Comment by frankwiles** [comment]
What Paul would like is to differentiate between a match on the full-text vs a match on the meta-data of the Document. 

If we can just show which of it matches in the search results that is fine.  Otherwise we should explore putting in 2 new indexes. 

1. Full-text only
2. Metadata only 
3. Keeping the originally stitched together version 

And then make it so if you pick 1 or 2, it deactivates 3 and vice versa.

**Comment by frankwiles** [comment]
Note: We can tell the difference if it's fulltext if it comes from this table `tblNurembergDocTexts`
