### ISSUE TITLE
Full-text transcript search: phrase search false positives

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#217]
In full-text exact phrase searching, many false positives being returned, as in screenshots below.

![full-text_search_phrase_search_false_positive_4](https://user-images.githubusercontent.com/1544067/227300541-0d356385-745f-4660-a23f-4b257645cfb7.jpg)

![full-text_search_phrase_search_false_positive_3](https://user-images.githubusercontent.com/1544067/227300548-3b3f687f-ac9f-4620-97c4-a7860163d821.jpg)

![full-text_search_phrase_search_false_positive_2](https://user-images.githubusercontent.com/1544067/227300551-a941f7a8-0e5d-4cad-94ac-e0f87cc38efb.jpg)

![full-text_search_phrase_search_false_positive](https://user-images.githubusercontent.com/1544067/227300556-c8a5154e-0258-4c60-89c0-f9474ae6c2f2.jpg)

**Comment by nessita** [comment]
cc @frankwiles 
This is another issue part of the group "Solr backend specific behavior that is also present in the original site". Adding the proper label and flagging Frank to decide next steps.

Reference URLs:
* https://nuremberg.revsys.dev/search/?q=%22in+the+end%22
* https://nuremberg.law.harvard.edu/search/?q=%22in+the+end%22

**Comment by frankwiles** [comment]
These all seem to be caused by what are known as "stop words" in search parlance.  They're words that are typically NOT included in the index because they are super common words and aren't useful in more typical search situations. 

I've attached the default list of English stop words Solr uses, we can not use these if you'd like but I'm not entirely sure what that will do to search relevancy for non-exact searches, but we can try it out easy enough. 
[stopwords.txt](https://github.com/revsys/revsys-nuremberg/files/11940881/stopwords.txt)
